version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: books_mysql
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booksDb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data: